export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",


  VERIFIY_RQUEST: "VERIFIY_RQUEST",
  VERIFIY_FAILURE: "VERIFIY_FAILURE",
  VERIFIY_SUCCESS: "VERIFIY_SUCCESS",

  RESEND_OTP_RQUEST: "RESEND_OTP_RQUEST",
  RESEND_OTP_FAILURE: "RESEND_OTP_FAILURE",
  RESEND_OTP_SUCCESS: "RESEND_OTP_SUCCESS",

  OTP_FOR_SIGNIN_RQUEST: "OTP_FOR_SIGNIN_RQUEST",
  OTP_FOR_SIGNIN_SUCCESS: "OTP_FOR_SIGNIN_SUCCESS",
  OTP_FOR_SIGNIN_FAILURE: "OTP_FOR_SIGNIN_FAILURE",
};

export const categoryContants = {
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
};

export const storePlansContants = {
  GET_ALL_STORE_PLANS_SUCCESS: "GET_ALL_STORE_PLANS_SUCCESS",

};

export const catalogContants = {
  GET_ALL_CATALOGS_REQUEST: "GET_ALL_CATALOGS_REQUEST",
  GET_ALL_CATALOGS_SUCCESS: "GET_ALL_CATALOGS_SUCCESS",
  GET_ALL_CATALOGS_FAILURE: "GET_ALL_CATALOGS_FAILURE",
  ADD_NEW_CATALOG_REQUEST: "ADD_NEW_CATALOG_REQUEST",
  ADD_NEW_CATALOG_SUCCESS: "ADD_NEW_CATALOG_SUCCESS",
  ADD_NEW_CATALOG_FAILURE: "ADD_NEW_CATALOG_FAILURE",

  DELETE_CATALOG_BY_ID_REQUEST: "DELETE_CATALOG_BY_ID_REQUEST",
  DELETE_CATALOG_BY_ID_SUCCESS: "DELETE_CATALOG_BY_ID_SUCCESS",
  DELETE_CATALOG_BY_ID_FAILURE: "DELETE_CATALOG_BY_ID_FAILURE",
  EDIT_CATALOG_BY_ID_REQUEST: "EDIT_CATALOG_BY_ID_REQUEST",
  EDIT_CATALOG_BY_ID_SUCCESS: "EDIT_CATALOG_BY_ID_SUCCESS",
  EDIT_CATALOG_BY_ID_FAILURE: "EDIT_CATALOG_BY_ID_FAILURE",


  GET_STORE_CATLALOG_DETAILS_BY_URL_REQUEST: "GET_STORE_CATLALOG_DETAILS_BY_URL_REQUEST",
  GET_STORE_CATLALOG_DETAILS_BY_URL_SUCCESS: "GET_STORE_CATLALOG_DETAILS_BY_URL_SUCCESS",
  GET_STORE_CATLALOG_DETAILS_BY_URL_FAILURE: "GET_STORE_CATLALOG_DETAILS_BY_URL_FAILURE"

};

export const orderContants = {
  EDIT_ORDER_PRODUCT_BY_ID_REQUEST: "EDIT_ORDER_PRODUCT_BY_ID_REQUEST",
  EDIT_ORDER_PRODUCT_BY_ID_SUCCESS: "EDIT_ORDER_PRODUCT_BY_ID_SUCCESS",
  EDIT_ORDER_PRODUCT_BY_ID_FAILURE: "EDIT_ORDER_PRODUCT_BY_ID_FAILURE",

  GET_ALL_STORE_ORDER_REQUEST: "GET_ALL_STORE_ORDER_REQUEST",
  GET_ALL_STORE_ORDER_SUCCESS: "GET_ALL_STORE_ORDER_SUCCESS",
  GET_ALL_STORE_ORDER_FAILURE: "GET_ALL_STORE_ORDER_FAILURE",
};

export const storeContants = {
  ADD_NEW_STORE_REQUEST: "ADD_NEW_STORE_REQUEST",
  ADD_NEW_STORE_SUCCESS: "ADD_NEW_STORE_SUCCESS",
  ADD_NEW_STORE_FAILURE: "ADD_NEW_STORE_FAILURE",

  GET_ALL_STORE_PRODUCTS_FAILURE: "GET_ALL_STORE_PRODUCTS_FAILURE",
  GET_ALL_STORE_PRODUCTS_SUCCESS: "GET_ALL_STORE_PRODUCTS_SUCCESS",

  EDIT_STORE_REQUEST: "EDIT_STORE_REQUEST",
  EDIT_STORE_SUCCESS: "EDIT_STORE_SUCCESS",
  EDIT_STORE_FAILURE: "EDIT_STORE_FAILURE",

  MARKETING_ADD_NEW_STORE_REQUEST: "MARKETING_ADD_NEW_STORE_REQUEST",
  MARKETING_ADD_NEW_STORE_SUCCESS: "MARKETING_ADD_NEW_STORE_SUCCESS",
  MARKETING_ADD_NEW_STORE_FAILURE: "MARKETING_ADD_NEW_STORE_FAILURE",

  OTP_FOR_STORE_SUCCESS: "OTP_FOR_STORE_SUCCESS",
  OTP_FOR_STORE_FAILURE: "OTP_FOR_STORE_FAILURE",
  OTP_FOR_STORE_REQUEST: "OTP_FOR_STORE_REQUEST",

  GET_STORE_DETAILS_BY_URL_REQUEST: "GET_STORE_DETAILS_BY_URL_REQUEST",
  GET_STORE_DETAILS_BY_URL_SUCCESS: "GET_STORE_DETAILS_BY_URL_SUCCESS",
  GET_STORE_DETAILS_BY_URL_FAILURE: "GET_STORE_DETAILS_BY_URL_FAILURE",


  CREATE_FREE_STORE_OTP_REQUEST: "CREATE_FREE_STORE_OTP_REQUEST",
  CREATE_FREE_STORE_OTP_SUCCESS: "CREATE_FREE_STORE_OTP_SUCCESS",
  CREATE_FREE_STORE_OTP_FAILURE: "CREATE_FREE_STORE_OTP_FAILURE",

  CREATE_FREE_STORE_OTP_VERIFY_REQUEST: "CREATE_FREE_STORE_OTP_VERIFY_REQUEST",
  CREATE_FREE_STORE_OTP_VERIFY_SUCCESS: "CREATE_FREE_STORE_OTP_VERIFY_SUCCESS",
  CREATE_FREE_STORE_OTP_VERIFY_FAILURE: "CREATE_FREE_STORE_OTP_VERIFY_FAILURE",

};

export const userInitialdata = {
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE",

};


export const sampleDataContants = {

  GET_ALL_SAMPLE_STORE: "GET_ALL_SAMPLE_STORE",
  GET_ALL_SAMPLE_PRODUCT: "GET_ALL_SAMPLE_PRODUCT",
  GET_ALL_SAMPLE_CATALOG: "GET_ALL_SAMPLE_CATALOG",

};

export const userStoreData = {
  GET_USER_STORE_DETAILS_SUCCESS: "GET_USER_STORE_DETAILS_SUCCESS",
  GET_USER__STORE_DETAILS_FAILURE: "GET_USER__STORE_DETAILS_FAILURE",
  GET_USER_STORE_DETAILS_EDIT_SUCCESS: "GET_USER_STORE_DETAILS_EDIT_SUCCESS",
  GET_USER__STORE_DETAILS_EDIT_FAILURE: "GET_USER__STORE_DETAILS_EDIT_FAILURE",
};

export const productContants = {

  ADD_NEW_PRODUCT_REQUEST: "ADD_NEW_PRODUCT_REQUEST",
  ADD_NEW_PRODUCT_SUCCESS: "ADD_NEW_PRODUCT_SUCCESS",
  ADD_NEW_PRODUCT_FAILURE: "ADD_NEW_PRODUCT_FAILURE",
  DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
  DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
  DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",
  EDIT_PRODUCT_BY_ID_REQUEST: "EDIT_PRODUCT_BY_ID_REQUEST",
  EDIT_PRODUCT_BY_ID_SUCCESS: "EDIT_PRODUCT_BY_ID_SUCCESS",
  EDIT_PRODUCT_BY_ID_FAILURE: "EDIT_PRODUCT_BY_ID_FAILURE",
  EDIT_PRODUCT_STOCK_BY_ID_SUCCESS: "EDIT_PRODUCT_STOCK_BY_ID_SUCCESS",

  GET_PRODUCT_DETAILS_BY_ID_REQUEST: "GET_PRODUCT_DETAILS_BY_ID_REQUEST",
  GET_PRODUCT_DETAILS_BY_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_ID_SUCCESS",
  GET_PRODUCT_DETAILS_BY_ID_FAILURE: "GET_PRODUCT_DETAILS_BY_ID_FAILURE",

  GET_STORE_PRODUCT_DETAILS_BY_URL_REQUEST: "GET_STORE_PRODUCT_DETAILS_BY_URL_REQUEST",
  GET_STORE_PRODUCT_DETAILS_BY_URL_SUCCESS: "GET_STORE_PRODUCT_DETAILS_BY_URL_SUCCESS",
  GET_STORE_PRODUCT_DETAILS_BY_URL_FAILURE: "GET_STORE_PRODUCT_DETAILS_BY_URL_FAILURE"

};

export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  RESET_CART: "RESET_CART",

  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
  REMOVE_CART_ITEM_SUCCESS1: "REMOVE_CART_ITEM_SUCCESS1",
  REMOVE_ALL_CART_ITEM_SUCCESS: "REMOVE_ALL_CART_ITEM_SUCCESS",

};


export const userContants = {
  ADD_USER_ADDRESS_REQUEST: "ADD_USER_ADDRESS_REQUEST",
  ADD_USER_ADDRESS_SUCCESS: "ADD_USER_ADDRESS_SUCCESS",
  ADD_USER_ADDRESS_FAILURE: "ADD_USER_ADDRESS_FAILURE",

  ADD_USER_ORDER_REQUEST: "ADD_USER_ORDER_REQUEST",
  ADD_USER_ORDER_SUCCESS: "ADD_USER_ORDER_SUCCESS",
  ADD_USER_ORDER_FAILURE: "ADD_USER_ORDER_FAILURE",

  GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
  GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
  GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",

  GET_USER_DETAILS_REQUEST: "GET_USER_DETAILS_REQUEST",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE",



  OTP_FOR_USER_SIGNIN_RQUEST: "OTP_FOR_USER_SIGNIN_RQUEST",
  OTP_FOR_USER_SIGNIN_SUCCESS: "OTP_FOR_USER_SIGNIN_SUCCESS",
  OTP_FOR_USER_SIGNIN_FAILURE: "OTP_FOR_USER_SIGNIN_FAILURE",


  VERIFIY_USER_OTP_RQUEST: "VERIFIY_USER_OTP_RQUEST",
  VERIFIY_USER_OTP_FAILURE: "VERIFIY_USER_OTP_FAILURE",
  VERIFIY_USER_OTP_SUCCESS: "VERIFIY_USER_OTP_SUCCESS",

  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",

};



export const credentialsContants = {
  GET_ALL_CREDENTIALS_REQUEST: "GET_ALL_CREDENTIALS_REQUEST",
  GET_ALL_CREDENTIALS_SUCCESS: "GET_ALL_CREDENTIALS_SUCCESS",
  GET_ALL_CREDENTIALS_FAILURE: "GET_ALL_CREDENTIALS_FAILURE",
}